propelsoa_generateobject_route:
    path:  /propelsoa/generate/object/{namespace}/{bundle}/{entity}
    defaults: { _controller: PropelSOABundle:ObjectGenerator:getObject }
propelsoa_generatepartialobject_route:
    path:  /propelsoa/generate/partialobject/{namespace}/{bundle}/{entity}
    defaults: { _controller: PropelSOABundle:ObjectGenerator:getPartialObject }
propelsoa_generatequery_route:
    path:  /propelsoa/generate/query/{namespace}/{bundle}/{entity}
    defaults: { _controller: PropelSOABundle:ObjectGenerator:getQuery }
propelsoa_generatecollection_route:
    path:  /propelsoa/generate/collection/{namespace}/{bundle}/{entity}
    defaults: { _controller: PropelSOABundle:ObjectGenerator:getCollection }
