PropelSOABundle_setdefaultcriteriaendpoint:
    path: /defaultCriteria/set/{fieldName}/{value}
    defaults: { _controller: PropelSOABundle:DefaultCriteria:setDefaultCriteria }
PropelSOABundle_getdefaultcriteriaendpoint:
    path: /defaultCriteria/get/{fieldName}
    defaults: { _controller: PropelSOABundle:DefaultCriteria:getDefaultCriteria }
PropelSOABundle_saveendpoint:
    path:  /save/{namespace}/{bundle}/{entity}
    defaults: { _controller: PropelSOABundle:Service:save }
PropelSOABundle_queryendpoint:
    path:  /service/{namespace}/{bundle}/{entity}
    defaults: { _controller: PropelSOABundle:Service:index }
PropelSOABundle_callendpoint:
    path:  /call/{namespace}/{bundle}/{entity}/{recordId}/{method}
    defaults: { _controller: PropelSOABundle:Service:call }
