parameters:
#    soasoa.example.class: ThirdEngine\PropelSOABundle\Example

services:
#    soasoa.example:
#        class: %soasoa.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
